### PR TITLE
Fixing issue with null properties on commit post body.

### LINKED ISSUE #8: Required fields that accepts null values
Hello again. Today I faced a new issue, but very similar than #7. 

We had some problems related to keep fields  with null value in sent json, right? Not I am facing a new error when a required field - that accepts null value - is not present in sent request, as example POST [/upload/{uploadSessionId}/commit](https://api.mangadex.org/docs/swagger.html#/Upload/commit-upload-session). There is required a `volume` field, but it can also be a null value. If we just exclude it from json, an error is returned and the operation is cancelled. 

```
400 - validation_exception - Error validating /chapterDraft/volume: The property volume is required
```

### PR DESCRIPTION
**Pull request by calico-crusade**
Should fix #8

### CODE REVIEW

File: src/MangaDexSharp/Models/Upload/UploadSessionCommit.cs [hunk 1]
```diff
@@ -50,12 +50,12 @@ public class ChapterDraft
...
-	[JsonPropertyName("externalUrl")]
+	[JsonPropertyName("externalUrl"), JsonIgnore(Condition = JsonIgnoreCondition.Never)]
 	public string? ExternalUrl { get; set; }
 
 	/// <summary>
 	/// When the chapter is to be published
 	/// </summary>
-	[JsonPropertyName("publishAt")]
+	[JsonPropertyName("publishAt"), JsonIgnore(Condition = JsonIgnoreCondition.Never)]
 	public DateTime? PublishAt { get; set; }
```
Comment (igorquintaes) [inline src/MangaDexSharp/Models/Upload/UploadSessionCommit.cs]: I think both properties needs to be ignored when null at request, based on [MangaDex API Swagger](https://api.mangadex.org/docs/swagger.html#/Upload/commit-upload-session), as i reported in #5. 

Probably all properties marked as required needs to be explicity written in json even if null; otherwise nonrequired props can't be present in json when null:

image

A weird behavior, if i can honestly say

Comment (calico-crusade) [reply src/MangaDexSharp/Models/Upload/UploadSessionCommit.cs]: This should be fixed in the latest commit. Let me know if it works and I'll merge and deploy. Thanks.

**Review by igorquintaes — APPROVED** [review]
